dual_fund_csv = [
    "msgtype,tx_add_input,66",
    "msgdata,tx_add_input,channel_id,channel_id,",
    "msgdata,tx_add_input,serial_id,u64,",
    "msgdata,tx_add_input,prevtx_len,u16,",
    "msgdata,tx_add_input,prevtx,byte,prevtx_len",
    "msgdata,tx_add_input,prevtx_vout,u32,",
    "msgdata,tx_add_input,sequence,u32,",
    # Removed script_sig fields
    "msgtype,tx_add_output,67",
    "msgdata,tx_add_output,channel_id,channel_id,",
    "msgdata,tx_add_output,serial_id,u64,",
    "msgdata,tx_add_output,sats,u64,",
    "msgdata,tx_add_output,scriptlen,u16,",
    "msgdata,tx_add_output,script,byte,scriptlen",
    "msgtype,tx_remove_input,68",
    "msgdata,tx_remove_input,channel_id,channel_id,",
    "msgdata,tx_remove_input,serial_id,u64,",
    "msgtype,tx_remove_output,69",
    "msgdata,tx_remove_output,channel_id,channel_id,",
    "msgdata,tx_remove_output,serial_id,u64,",
    "msgtype,tx_complete,70",
    "msgdata,tx_complete,channel_id,channel_id,",
    "msgtype,tx_signatures,71",
    "msgdata,tx_signatures,channel_id,channel_id,",
    "msgdata,tx_signatures,txid,sha256,",
    "msgdata,tx_signatures,num_witnesses,u16,",
    "msgdata,tx_signatures,witness_stack,witness_stack,num_witnesses",
    "subtype,witness_stack",
    "subtypedata,witness_stack,num_input_witness,u16,",
    "subtypedata,witness_stack,witness_element,witness_element,num_input_witness",
    "subtype,witness_element",
    "subtypedata,witness_element,len,u16,",
    "subtypedata,witness_element,witness,byte,len",
    # Add TX_INIT_RBF message
    "msgtype,tx_init_rbf,72",
    "msgdata,tx_init_rbf,channel_id,channel_id,",
    "msgdata,tx_init_rbf,locktime,u32,",
    "msgdata,tx_init_rbf,feerate,u32,",
    "tlvtype,tx_init_rbf_tlvs,funding_output_contribution,0",
    "tlvdata,tx_init_rbf_tlvs,funding_output_contribution,satoshis,tu64,",
    # Add TX_ACK_RBF message
    "msgtype,tx_ack_rbf,73", 
    "msgdata,tx_ack_rbf,channel_id,channel_id,",
    "tlvtype,tx_ack_rbf_tlvs,funding_output_contribution,0",
    "tlvdata,tx_ack_rbf_tlvs,funding_output_contribution,satoshis,tu64,",
    # Add TX_ABORT message
    "msgtype,tx_abort,74",
    "msgdata,tx_abort,channel_id,channel_id,",
    "msgdata,tx_abort,len,u16,",
    "msgdata,tx_abort,data,byte,len",
    # Update open_channel2
    "msgtype,open_channel2,64",
    "msgdata,open_channel2,chain_hash,chain_hash,",
    "msgdata,open_channel2,zerod_channel_id,channel_id,",  # Changed from channel_id
    "msgdata,open_channel2,funding_feerate_perkw,u32,",
    "msgdata,open_channel2,commitment_feerate_perkw,u32,",
    "msgdata,open_channel2,funding_satoshis,u64,",
    "msgdata,open_channel2,dust_limit_satoshis,u64,",
    "msgdata,open_channel2,max_htlc_value_in_flight_msat,u64,",
    "msgdata,open_channel2,htlc_minimum_msat,u64,",
    "msgdata,open_channel2,to_self_delay,u16,",
    "msgdata,open_channel2,max_accepted_htlcs,u16,",
    "msgdata,open_channel2,locktime,u32,",
    "msgdata,open_channel2,funding_pubkey,point,",
    "msgdata,open_channel2,revocation_basepoint,point,",
    "msgdata,open_channel2,payment_basepoint,point,",
    "msgdata,open_channel2,delayed_payment_basepoint,point,",
    "msgdata,open_channel2,htlc_basepoint,point,",
    "msgdata,open_channel2,first_per_commitment_point,point,",
    "msgdata,open_channel2,channel_flags,byte,",
    "msgdata,open_channel2,tlvs,opening_tlvs,",
    # Updated TLV types
    "tlvtype,opening_tlvs,upfront_shutdown_script,0",
    "tlvdata,opening_tlvs,upfront_shutdown_script,shutdown_scriptpubkey,byte,...",
    "tlvtype,opening_tlvs,channel_type,1",
    "tlvdata,opening_tlvs,channel_type,type,byte,...",
    # Updated accept_channel2
    "msgtype,accept_channel2,65",
    "msgdata,accept_channel2,zerod_channel_id,channel_id,",  # Changed from channel_id
    "msgdata,accept_channel2,funding_satoshis,u64,",
    "msgdata,accept_channel2,dust_limit_satoshis,u64,",
    "msgdata,accept_channel2,max_htlc_value_in_flight_msat,u64,",
    "msgdata,accept_channel2,htlc_minimum_msat,u64,",
    "msgdata,accept_channel2,minimum_depth,u32,",
    "msgdata,accept_channel2,to_self_delay,u16,",
    "msgdata,accept_channel2,max_accepted_htlcs,u16,",
    "msgdata,accept_channel2,funding_pubkey,point,",
    "msgdata,accept_channel2,revocation_basepoint,point,",
    "msgdata,accept_channel2,payment_basepoint,point,",
    "msgdata,accept_channel2,delayed_payment_basepoint,point,",
    "msgdata,accept_channel2,htlc_basepoint,point,",
    "msgdata,accept_channel2,first_per_commitment_point,point,",
    "msgdata,accept_channel2,tlvs,accept_tlvs,",
    # Updated TLV types
    "tlvtype,accept_tlvs,upfront_shutdown_script,0",
    "tlvdata,accept_tlvs,upfront_shutdown_script,shutdown_scriptpubkey,byte,...",
    "tlvtype,accept_tlvs,channel_type,1",
    "tlvdata,accept_tlvs,channel_type,type,byte,...",
    # Remove old init_rbf and ack_rbf
]

# This is https://github.com/lightningnetwork/lightning-rfc/pull/880
channel_type_csv = [
    "tlvtype,open_channel_tlvs,channel_type,1",
    "tlvdata,open_channel_tlvs,channel_type,type,byte,...",
    "tlvtype,accept_channel_tlvs,channel_type,1",
    "tlvdata,accept_channel_tlvs,channel_type,type,byte,...",
]
